name: Gradle Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Build Distribution
        run: ./gradlew assembleDist -Pversion=${{ github.event.inputs.release_version }}

      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: v${{ github.event.inputs.release_version }}
          body: "Automated release for version ${{ github.event.inputs.release_version }}"
          draft: false
          prerelease: false
          files: |
            build/distributions/*
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}